### ISSUE TITLE
How to cinfig server and launch it after via it?

### ISSUE THREAD

**Issue by IMRastafari** [gavinnn101/palworld_dedi_helper#5]
HI, i dont know how to python, but managed to install in and 2 additional extentions u said.
THen i got stuck cant figure out how to lauch server via it and how to set it up properly?
I found some server settings in palworld_util.py.
I even have put my server data in it, saved file, i thought it will be like server settings. Then i went back to example file, tried to lanched it - just 1 sec console and it closes, Same with server file.  Nothing happened.

How to use it? Any manual?

**Comment by IMRastafari** [comment]
I thought i figured out exampel ho to use it - added server details, used cmd, opened that fila fia cmd, but it get that error.

"Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\IMRastafari>C:\Users\IMRastafari\Desktop\palworld_dedi_helper-main\src\example.py
Traceback (most recent call last):
  File "C:\Users\IMRastafari\Desktop\palworld_dedi_helper-main\src\example.py", line 13, in <module>
    RCON_PORT = int(os.getenv("25575"))
                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

C:\Users\IMRastafari>"

**Comment by gavinnn101** [comment]
[These lines](https://github.com/gavinnn101/palworld_dedi_helper/blob/main/src/example.py#L9-L13) are what sets your server settings in `example.py`. These lines are looking for environment variable values which you likely aren't setting. If you don't want to use environment variables, you can change the lines to something like:

```
STEAMCMD_DIR = "my/steamcmd/dir/path"
SERVER_NAME = "My palworld server"
SERVER_IP = "1.1.1.1.1"
RCON_PASSWORD = "my_rcon_password"
RCON_PORT =27015
```
