### ISSUE TITLE
Getting this error sometime. HOw to fix?

### ISSUE THREAD

**Issue by IMRastafari** [gavinnn101/palworld_dedi_helper#6]
Hi, all workign fine exept this. whe it tries to broadcast.
"2024-02-12 14:00:18.011 | ERROR    | palworld_rcon.source_rcon:establish_connection:132 - Error while establishing a connection: [WinError 10061] No connection could be made because the target machine actively refused it"

**Comment by IMRastafari** [comment]
![image](https://github.com/gavinnn101/palworld_dedi_helper/assets/16764950/7e94bcf1-a463-4b38-84a6-ff240188d911)
Port environment and pass is set up. Other rcon plguins and mods are working. 
Got it when server_watcher tried to broadcast after restart 2024-02-12 14:00:15.975 | INFO     | utility.palworld_util:log_and_broadcast:115 - Next server restart in: 360 minutes
2024-02-12 14:00:18.011 | ERROR    | palworld_rcon.source_rcon:establish_connection:132 - Error while establishing a connection: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by gavinnn101** [comment]
This is expected. The script tries to `log_and_broadcast()` the next server restart but the server is likely still starting up so it logs to console and the broadcast to the server fails. The exception is caught and the script will continue as normal.

I'll look later when I have time to see if it can watch for the server process before sending the broadcast.

**Comment by gavinnn101** [comment]
Fixed in [latest commit](https://github.com/gavinnn101/palworld_dedi_helper/commit/a3eee2d5001eac676b8aa7858e0b3a94daafe110)

If `WAIT_FOR_RCON_PORT = True` it will wait until it can make a connection to your `$server_ip:$rcon_port` or until it hits `WAIT_FOR_RCON_PORT_TIMEOUT`.

I did some quick testing and it fixes the bug mentioned in [comment#2](https://github.com/gavinnn101/palworld_dedi_helper/issues/6#issuecomment-1938516206).

**Comment by IMRastafari** [comment]
BTW - is there a way to save config and udate it without losing it every time? CAuse after files update have to change all restart\save plus you missing  EpicApp=PalServer  in settings, have to add it manualy every time. 
And now i found out that py file stoped runnig, where to find info why it happeend?
