### ISSUE TITLE
Add EPICAPP=Plaserver to default config

### ISSUE THREAD

**Issue by IMRastafari** [gavinnn101/palworld_dedi_helper#8]
Pls add to default config that string with epicapp so servers dont lose their community status when using your soft.
https://tech.palworldgame.com/getting-started/deploy-community-server/
Without it its not getting pinged by Epic games api https://github.com/gamedig/node-gamedig/blob/master/protocols/palworld.js and servers ratings sites cant see server online and send some queries there.

**Comment by IMRastafari** [comment]
Is project abandoned? ANy updates with new palserver parameters? Need -publiclobby.

**Comment by gavinnn101** [comment]
With commit https://github.com/gavinnn101/palworld_dedi_helper/commit/2fff84fc85a626af1c8370d3a03755afd0800119 you can now pass `public_server = True` to PalworldUtil to add the `-publiclobby` launch option.
